on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - run: npm run test
